### ISSUE TITLE
Vercel部署失败

### ISSUE THREAD

**Issue by TTsdzb** [auroral-ui/hexo-plugin-aurora#14]
在最近两次更新后（`1.8.0` 和 `1.8.1`）的自动部署均失败。

以下日志生成时的主题版本为 `2.5.0`，插件版本为 `1.8.1`。`1.8.0` 的插件报错与之相似。

```
[08:40:51] Running build in Cleveland, USA (East) – cle1
[08:40:51] Cloning github.com/TTsdzb/ttsdzb-blog (Branch: dependabot/npm_and_yarn/hexo-plugin-aurora-1.8.1, Commit: 1bc118f)
[08:40:51] Cloning completed: 512.232ms
[08:40:52] Restored build cache
[08:40:52] Running "vercel build"
[08:40:52] Vercel CLI 32.2.1
[08:40:53] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[08:40:53] Installing dependencies...
[08:40:54] Lockfile is up to date, resolution step is skipped
[08:40:54] Progress: resolved 1, reused 0, downloaded 0, added 0
[08:40:54] Packages: +27 -1
[08:40:54] +++++++++++++++++++++++++++-
[08:40:54] Progress: resolved 27, reused 0, downloaded 27, added 27, done
[08:40:54] .../deasync@0.1.28/node_modules/deasync install$ node ./build.js
[08:40:54] .../deasync@0.1.28/node_modules/deasync install: `linux-x64-node-18` exists; testing
[08:40:54] .../deasync@0.1.28/node_modules/deasync install: Binary is fine; exiting
[08:40:54] .../deasync@0.1.28/node_modules/deasync install: Done
[08:40:55] 
[08:40:55] dependencies:
[08:40:55] - hexo-plugin-aurora 1.7.0
[08:40:55] + hexo-plugin-aurora 1.8.1
[08:40:55] 
[08:40:55] Done in 1.5s
[08:40:55] Running "pnpm run build"
[08:40:55] 
[08:40:55] > ttsdzb-hexo@0.0.0 build /vercel/path0
[08:40:55] > hexo generate
[08:40:55] 
[08:40:56] [32mINFO [39m Validating config
[08:40:56] [32mINFO [39m Start processing
[08:40:56] [41mFATAL[49m Something's wrong. Maybe you can find the solution here: [4mhttps://hexo.io/docs/troubleshooting.html[24m
[08:40:56] [33mTypeError: Cannot read properties of undefined (reading 'tip')
[08:40:56]     at /vercel/path0/node_modules/.pnpm/hexo-plugin-aurora@1.8.1/node_modules/hexo-plugin-aurora/lib/filters/afterPostRender/quote.js:94:46
[08:40:56]     at String.replace (<anonymous>)
[08:40:56]     at Hexo.filterCustomQuote (/vercel/path0/node_modules/.pnpm/hexo-plugin-aurora@1.8.1/node_modules/hexo-plugin-aurora/lib/filters/afterPostRender/quote.js:88:8)
[08:40:56]     at Hexo.tryCatcher (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/util.js:16:23)
[08:40:56]     at Hexo.<anonymous> (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/method.js:15:34)
[08:40:56]     at /vercel/path0/node_modules/.pnpm/hexo@6.3.0/node_modules/hexo/lib/extend/filter.js:67:52
[08:40:56]     at tryCatcher (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/util.js:16:23)
[08:40:56]     at Object.gotValue (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/reduce.js:166:18)
[08:40:56]     at Object.gotAccum (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/reduce.js:155:25)
[08:40:56]     at Object.tryCatcher (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/util.js:16:23)
[08:40:56]     at Promise._settlePromiseFromHandler (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:547:31)
[08:40:56]     at Promise._settlePromise (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:604:18)
[08:40:56]     at Promise._settlePromise0 (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:649:10)
[08:40:56]     at Promise._settlePromises (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:729:18)
[08:40:56]     at _drainQueueStep (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:93:12)
[08:40:56]     at _drainQueue (/vercel/path0/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:86:9)[39m
[08:40:56] INFO  Thanks for using: hexo-plugin-aurora v1.8.1 & hexo-theme-aurora v2.5.0
[08:40:56] INFO  Crafted by bennyxguo <三钻>
[08:40:56]  ELIFECYCLE  Command failed with exit code 2.
[08:40:56] Error: Command "pnpm run build" exited with 1
```

**Comment by bennyxguo** [comment]
升级了版本 2.5 之后，你的 site 语言配置是不是没有改?

看着这里改一下应该就没有问题了。
https://aurora.tridiamond.tech/cn/upgrade/v2.5.html#%E5%8D%87%E7%BA%A7%E8%AF%AD%E8%A8%80%E9%85%8D%E7%BD%AE

**Comment by TTsdzb** [comment]
改过之后可以了。感谢！

另外建议需要改配置的时候在 CHANGELOG 里作为 Breaking Change 添上，这样很容易就看出来需要改了。
