### ISSUE TITLE
[Aurora Config Error] Missing site_meta and site attributes

### ISSUE THREAD

**Issue by WilliamWang1721** [auroral-ui/hexo-plugin-aurora#28]
Hello,

I'm experiencing issues with the Aurora theme for Hexo. During the setup, I encountered the following errors:

1. `site_meta is not configured`
2. `Theme config site attribute is missing`

I have followed the setup instructions but still encounter these issues. I have ensured that the `_config.aurora.yml` file contains the required `site_meta` and `site` configurations.

Error log:
hexo clean
hexo g
hexo s
INFO  Validating config
[Aurora Config Error] site_meta is not configured, please provide the site-meta configure in _config.aurora.yml
[ERROR] Please create an issue @ https://github.com/auroral-ui/hexo-plugin-aurora/issues with the above error message. Thanks!
请在 @https://github.com/auroral-ui/hexo-plugin-aurora/issues 提交一个 issue, 并附带以上报错信息, 谢谢！
INFO  Deleted database.
INFO  Deleted public folder.
INFO  Thanks for using: hexo-plugin-aurora v1.8.4 & hexo-theme-aurora v0.0.0-semantic-release
INFO  Crafted by bennyxguo <三钻>
INFO  Validating config
[Aurora Config Error] site_meta is not configured, please provide the site-meta configure in _config.aurora.yml
[ERROR] Please create an issue @ https://github.com/auroral-ui/hexo-plugin-aurora/issues with the above error message. Thanks!
请在 @https://github.com/auroral-ui/hexo-plugin-aurora/issues 提交一个 issue, 并附带以上报错信息, 谢谢！
INFO  Start processing
[Aurora Config Error] Theme config site attribute is missing, please check the theme config template here: https://github.com/auroral-ui/hexo-theme-aurora/blob/main/_config.yml.
[ERROR] Please create an issue @ https://github.com/auroral-ui/hexo-plugin-aurora/issues with the above error message. Thanks!
请在 @https://github.com/auroral-ui/hexo-plugin-aurora/issues 提交一个 issue, 并附带以上报错信息, 谢谢！
[Aurora Config Error] Theme config site attribute is missing, please check the theme config template here: https://github.com/auroral-ui/hexo-theme-aurora/blob/main/_config.yml.
[ERROR] Please create an issue @ https://github.com/auroral-ui/hexo-plugin-aurora/issues with the above error message. Thanks!
请在 @https://github.com/auroral-ui/hexo-plugin-aurora/issues 提交一个 issue, 并附带以上报错信息, 谢谢！
[Aurora Config Error] Theme config site attribute is missing, please check the theme config template here: https://github.com/auroral-ui/hexo-theme-aurora/blob/main/_config.yml.
[ERROR] Please create an issue @ https://github.com/auroral-ui/hexo-plugin-aurora/issues with the above error message. Thanks!
请在 @https://github.com/auroral-ui/hexo-plugin-aurora/issues 提交一个 issue, 并附带以上报错信息, 谢谢！
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read properties of undefined (reading 'Tags')
    at /Users/williamwang/blog/node_modules/hexo-plugin-aurora/lib/generators/index.js:39:27
    at Array.forEach (<anonymous>)
    at Hexo.<anonymous> (/Users/williamwang/blog/node_modules/hexo-plugin-aurora/lib/generators/index.js:38:18)
    at Hexo.tryCatcher (/Users/williamwang/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/williamwang/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/williamwang/blog/node_modules/hexo/dist/hexo/index.js:340:28
    at tryCatcher (/Users/williamwang/blog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/williamwang/blog/node_modules/bluebird/js/release/map.js:68:38)
    at PromiseArray._iterate (/Users/williamwang/blog/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/williamwang/blog/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/williamwang/blog/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/williamwang/blog/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/williamwang/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/williamwang/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/williamwang/blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)
INFO  Thanks for using: hexo-plugin-aurora v1.8.4 & hexo-theme-aurora v0.0.0-semantic-release
INFO  Crafted by bennyxguo <三钻>
INFO  Validating config
[Aurora Config Error] site_meta is not configured, please provide the site-meta configure in _config.aurora.yml
[ERROR] Please create an issue @ https://github.com/auroral-ui/hexo-plugin-aurora/issues with the above error message. Thanks!
请在 @https://github.com/auroral-ui/hexo-plugin-aurora/issues 提交一个 issue, 并附带以上报错信息, 谢谢！
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read properties of undefined (reading 'Tags')
    at /Users/williamwang/blog/node_modules/hexo-plugin-aurora/lib/generators/index.js:39:27
    at Array.forEach (<anonymous>)
    at Hexo.<anonymous> (/Users/williamwang/blog/node_modules/hexo-plugin-aurora/lib/generators/index.js:38:18)
    at Hexo.tryCatcher (/Users/williamwang/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/williamwang/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/williamwang/blog/node_modules/hexo/dist/hexo/index.js:340:28
    at tryCatcher (/Users/williamwang/blog/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/williamwang/blog/node_modules/bluebird/js/release/map.js:68:38)
    at PromiseArray._iterate (/Users/williamwang/blog/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/williamwang/blog/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/williamwang/blog/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/williamwang/blog/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/williamwang/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/williamwang/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/williamwang/blog/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:483:21)
INFO  Thanks for using: hexo-plugin-aurora v1.8.4 & hexo-theme-aurora v0.0.0-semantic-release
INFO  Crafted by bennyxguo <三钻>

Could you please assist in resolving this issue?

Thank you!

**Comment by WilliamWang1721** [comment]
hexo clean
INFO  Validating config
[Aurora Config Error] site_meta is not configured, please provide the site-meta configure in _config.aurora.yml
[ERROR] Please create an issue @ https://github.com/auroral-ui/hexo-plugin-aurora/issues with the above error message. Thanks!
请在 @https://github.com/auroral-ui/hexo-plugin-aurora/issues 提交一个 issue, 并附带以上报错信息, 谢谢！
INFO  Thanks for using: hexo-plugin-aurora v1.8.4 & hexo-theme-aurora v0.0.0-semantic-release
INFO  Crafted by bennyxguo <三钻>

**Comment by Dentist-Y** [comment]
INFO  Validating config
[Aurora Config Error] site_meta is not configured, please provide the site-meta
configure in _config.aurora.yml
[ERROR] Please create an issue @ https://github.com/auroral-ui/hexo-plugin-auror
a/issues with the above error message. Thanks!
请在 @https://github.com/auroral-ui/hexo-plugin-aurora/issues 提交一个 issue, 并
附带以上报错信息, 谢谢！
INFO  Deleted database.
INFO  Deleted public folder.
INFO  Thanks for using: hexo-plugin-aurora v1.8.4 & hexo-theme-aurora v2.5.3
INFO  Crafted by bennyxguo <三钻>
